#!/usr/bin/env bash

resources_path=$(dirname "${BASH_SOURCE}")/../resources

cp -n $resources_path/overview.{js,css,css.map} "$KLAB_REPORT_DIR"
cp -n $resources_path/report.{css,css.map} "$KLAB_REPORT_DIR"
cp -n $resources_path/overview.html "$KLAB_REPORT_DIR"/"$1"/index.html


