#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const AWS = require('aws-sdk');
const {
  testPath,
  read
} = require("../lib/util.js");

// TODO - check if env variable are set correctly
AWS.config.update({ accessKeyId: process.env.KLAB_PUBLISH_ID, secretAccessKey: process.env.KLAB_PUBLISH_SECRET });
const s3 = new AWS.S3();

const KLAB_WD_PATH = path.join(process.env.TMPDIR, "klab");

const proofid = process.argv[2];
const pruned_path = path.join(KLAB_WD_PATH, `boot_${proofid}.json`);
const boot_json_str = read(pruned_path);

console.log(`uploading`);

const push = (name, data, cb) => s3.putObject({
  Bucket: 'dapphub-klab-player',
  Key: name,
  Body: data,
  ACL: 'public-read'
}, cb);

push(`boot_${proofid}.json`, boot_json_str, (err, res) => {
  console.log("ready");
})
