#!/usr/bin/env bash

if [ -z "$KLAB_OUT" ]; then
  KLAB_OUT=out
fi


if [ -z "$1" ]; then
  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
  if [ -z $spec_hash ]; then
    echo "ERROR: $1 no spec or active HEAD found"
    exit 1;
  fi
else
  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
  else
    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
      spec_hash="$1"
    else
      echo "ERROR: $1 is unknown"
      exit 1;
    fi;
  fi;
fi

spec_name=$(jq -r ".name" < "$KLAB_OUT/meta/data/$spec_hash")


if [ ! -d "$KLAB_OUT/log" ]; then
    mkdir -p "$KLAB_OUT/log"
fi

cd $KLAB_OUT
find . \
  \( -name "*$spec_hash*" \
  -o -name "*$spec_name*" \
  -o -name config.tmp.json \
  -o -name prelude.smt2 \
  -o -name rules.k \
  -o -name bin_runtime.k \) \
  -a \! -name "*.tar" \
  -a \! -name "*.zip" \
  -exec tar --create --zstd --file "./log/$spec_hash.tar" {} +
