#!/usr/bin/env bash
set -e

if [ -z "$KLAB_OUT" ]; then
  KLAB_OUT=out
fi

url=$1

mkdir -p "$KLAB_OUT"/log
wget "$url" -P "$KLAB_OUT"/log/
unzip -qu "$KLAB_OUT/log/${url##*/}" -d "$KLAB_OUT"
# log the proof hash
hash=$(basename "$url" '.zip')
echo $hash > $KLAB_OUT/HEAD
echo "Focusing on: $hash"
