#!/bin/sh

if [ -f out/meta/$1 ]; then
  echo "ERROR: proof with hash '$1' not found."
  exit 1
fi

spec_name=$(cat out/meta/data/$1 |jq -r '.name')

zip -r out/log/$1.zip \
  out/{data,pass,fail,meta/data,gas}/$1* \
  out/specs/${spec_name}.k \
  >/dev/null

