#!/usr/bin/env node

const {docopt}      = require("docopt");

const {
  getId
} = require("../lib/util/util.js");

const usage = `
Usage:
  klab hash [options] <spec>
`

const cmd = docopt(usage, {
  argv: ["hash"].concat(process.argv.slice(2))
});

process.stdout.write(getId(cmd["<spec>"]))
