#!/usr/bin/env bash
set -e
if [ -z "$KLAB_OUT" ]; then
  KLAB_OUT=out
fi
export GAS_DIR=$KLAB_OUT/gas

if [ -z "$1" ]; then
  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
  if [ -z $spec_hash ]; then
    echo "ERROR: $1 no spec or active HEAD found"
    exit 1;
  fi
else
  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
  else
    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
      spec_hash="$1"
    else
      echo "ERROR: $1 is unknown"
      exit 1;
    fi;
  fi;
fi

name=$(cat "$KLAB_OUT/meta/data/$spec_hash"| jq -r ".name")

klab gas-analyser --stratification-label $name --input "$GAS_DIR/${spec_hash}.all.json" > "$GAS_DIR/${spec_hash}.kast"
result_solved=$?
klab gas-analyser --no-solve --stratification-label ${name}_raw --input "$GAS_DIR/${spec_hash}.all.json" > "$GAS_DIR/${spec_hash}.raw.kast"
result_raw=$?

if [ $result_solved -ne "0" ] || [ $result_raw -ne "0" ]; then
  rm "$GAS_DIR/${spec_hash}.kast"
  rm "$GAS_DIR/${spec_hash}.raw.kast"
  exit 1;
fi
