#!/usr/bin/env bash

if [ -z "$KLAB_OUT" ]; then
  echo "KLAB_OUT not set, defaulting to ./out/"
  KLAB_OUT=out
fi

if [ -f "$KLAB_OUT/meta/data/$1" ] ; then
    spec_name=$(jq -r '.name' < "$KLAB_OUT/meta/data/$1")
else
    spec_name="$1";
fi

if [ ! -d "out/log" ]; then
    mkdir -p out/log
fi

find out/ \
     \( -wholename "*$1*" -or -wholename "*$spec_name*" \) \
     -and ! -wholename "out/log/*" \
     -exec zip "out/log/$1.zip" {} +

zip -r "out/log/$1.zip" \
    out/prelude.smt2 \
    out/rules.k \
    config.json
