#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const AWS = require('aws-sdk');
const {docopt}      = require("docopt");
const Config        = require("../lib/config.js");
const {
  testPath,
  revert,
  read,
  sha3
} = require("../lib/util.js");
const config_json   = JSON.parse(fs.readFileSync("./config.json"));
const config        = Config(config_json);

const usage = `
Usage:
  klab publish [options]

Options:
  --spec=<spec>
`

const cmd = docopt(usage, {
  argv: ["publish"].concat(process.argv.slice(2))
});

try {
  config.out = JSON.parse(fs.readFileSync("out/out.json"))
} catch(e) {
}

config.spec = cmd["--spec"] && (
    testPath(cmd["--spec"]) && read(cmd["--spec"])
    || revert(`spec not found at ${cmd["--spec"]}`))

config.name = cmd["--spec"] && path.basename(cmd["--spec"])
  || cmd["--name"] && ("proof-" + name + ".k")

config.rules = testPath("out/rules.k") && read("out/rules.k")
  || revert("no rules found at out/rules.k")

config.smt_prelude = testPath("out/prelude.smt2") && read("out/prelude.smt2")
  || revert("no smt prelude file at out/prelude.mst2")

const proofid = sha3(JSON.stringify({
  rules: config.rules,
  spec : config.spec,
  smt_prelude: config.smt_prelude
}));

// TODO - check if env variable are set correctly
AWS.config.update({ accessKeyId: process.env.KLAB_PUBLISH_ID, secretAccessKey: process.env.KLAB_PUBLISH_SECRET });
const s3 = new AWS.S3();

const KLAB_LOG_PATH = path.join("out", "log");
const pruned_path = path.join(KLAB_LOG_PATH, `boot_${proofid}.json`);
const boot_json_str = read(pruned_path);

console.log(`uploading`);

const push = (name, data, cb) => s3.putObject({
  Bucket: 'dapphub-klab-player',
  Key: name,
  Body: data,
  ACL: 'public-read'
}, cb);

push(`boot_${proofid}.json`, boot_json_str, (err, res) => {
  console.log("ready");
})
