#!/usr/bin/env node
const xs = require("xstream").default;
const {run} = require("@cycle/run");
const {docopt} = require("docopt");
const fs = require("fs");

// TODO - klab debug should not care about the config.js
const path = require("path");
const makeConfig = require("../lib/config.js");
process.title = "klab";

const makeCliDriver = require("../lib/driver/cliDriver.js")
const remoteDriver = require("../lib/driver/remoteDriver.js")
const makeDumpDriver = require("../lib/driver/dumpDriver.js");
const main = require("../lib/main.js")
const {
  testPath,
  revert,
  warn,
  read,
  sha3
} = require("../lib/util/util.js");

const usage = `
Usage:
  klab debug [options] <spec>

Options:
  --force               No replay
  --inspect=<id>
  --clean
  --headless
  --filter-oog
  --shamefully-trust-dependencies
`

const KLAB_OUT = process.env.KLAB_OUT || "out";

const cmd = docopt(usage, {
  argv: ["debug"].concat(process.argv.slice(2))
});

const config_json = JSON.parse(fs.readFileSync("./config.json"));
const config = makeConfig(config_json, cmd["<spec>"]);

const specs       = fs.readdirSync(path.join(KLAB_OUT, "specs"));
const spec_names  = specs.map(s => s.slice(0, -2))
const TRUST_DEPENDENCIES = cmd["--shamefully-trust-dependencies"] || false;

config.rules = testPath(path.join(KLAB_OUT, "rules.k")) && read(path.join(KLAB_OUT, "rules.k"))
  || revert(`no rules found at ${KLAB_OUT}/rules.k`)

config.smt_prelude = testPath(path.join(KLAB_OUT, "prelude.smt2")) && read(path.join(KLAB_OUT, "prelude.smt2"))
  || revert(`no smt prelude file at ${KLAB_OUT}/prelude.mst2`)

config.FILTER_OOG = cmd["--filter-oog"] || false;

// proof id
config.proofid = sha3(JSON.stringify({
  rules: config.rules,
  spec : config.spec,
  smt_prelude: config.smt_prelude
}));

config.connection = {
  type: "remote",
  host: config.host || "127.0.0.1:8080"
}

const kDriver = remoteDriver(config.host);
// const inspect = cmd["--inspect"];
// if(inspect) config.inspect = inspect;

config.force = cmd["--force"];

const CLIDriver = cmd["--headless"]
  ? () => xs.of()
  : makeCliDriver({
    // type: "console",
    // in: false
  })
config.headless = cmd["--headless"]

const dumpDriver  = makeDumpDriver(config);

const drivers = {
  CLI: CLIDriver,
  K: kDriver,
  Settings: () => xs.of(config),
  Dump: dumpDriver
};

run(main, drivers)
