#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const {docopt}      = require("docopt");
const {
  testPath,
  read,
  ensureDir,
  sha3
} = require("../lib/util.js");
const {
  prune_edges,
} = require("../lib/compile.js");

const KLAB_WD_PATH = path.join(process.env.TMPDIR, "klab");
const KLAB_OUT     = process.env.KLAB_OUT || "out";

const usage = `
Usage:
  klab compile-edges [options] <hash>

Options:
  --prune
`

const cmd = docopt(usage, {
  argv: ["compile-edges"].concat(process.argv.slice(2))
});
const PRUNE         = cmd["--prune"] || false;
const proofid = cmd['<hash>'];

// TODO - ensure proofid exists and is readable


const {pruned_edges, initt, finished} = prune_edges(proofid, PRUNE);

ensureDir(path.join(KLAB_OUT, "compiled"));
ensureDir(path.join(KLAB_OUT, "compiled", proofid));

fs.writeFileSync(path.join(KLAB_OUT, "compiled", proofid, 'edges.json'), JSON.stringify(pruned_edges));
