#!/usr/bin/env bash

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
bold=$(tput bold)
reset=$(tput sgr0)

if [ -z "$KLAB_OUT" ]; then
    export KLAB_OUT=out
fi

if [ -z "$1" ]; then
  spec_hash=${KLAB_HEAD:-$(cat "$KLAB_OUT/HEAD")}
  if [ -z $spec_hash ]; then
    echo "ERROR: $1 no spec or active HEAD found"
    exit 1;
  fi
else
  if [ -f "$KLAB_OUT/meta/name/$1" ]; then
    spec_hash=$(cat "$KLAB_OUT/meta/name/$1")
  else
    if [ -f "$KLAB_OUT/meta/data/$1" ]; then
      spec_hash="$1"
    else
      echo "ERROR: $1 is unknown"
      exit 1;
    fi;
  fi;
fi

name=$(jq -r ".name" < "$KLAB_OUT/meta/data/$spec_hash")

echo "$name"
echo "$spec_hash "
status="unknown"
if [ -f "$KLAB_OUT/accept/$spec_hash" ]; then
  status="${green}${bold}ACCEPT${reset}"
fi;
if [ -f "$KLAB_OUT/reject/$spec_hash" ]; then
  status="${red}${bold}REJECT${reset}"
fi;
echo "status: $status"
