#!/bin/sh
echo "Commands:
klab build [options] <spec>
klab debug [options] <spec>
klab prove [options] <spec>

klab build options:
  --filter=<filter>
  --trust
  --debug
  --no-oog
`

klab debug options:
  --force               No replay
  --inspect=<id>
  --headless
  --filter-oog
"
