#!/usr/bin/env bash

hash_or_name=$1

if [ -z "$KLAB_OUT" ]; then
  KLAB_OUT=out
fi

if [ -f "$KLAB_OUT/meta/name/$hash_or_name" ]; then
  hash=$(cat "$KLAB_OUT/meta/name/$hash_or_name")
else
  if [ -f "$KLAB_OUT/meta/data/$hash_or_name" ]; then
    hash="$hash_or_name"
  else
    echo "ERROR: $hash_or_name is unknown"
    exit 1;
  fi;
fi;
name=$(jq -r ".name" < "$KLAB_OUT/meta/data/$hash")

echo "$hash $name";
echo "$hash" > "$KLAB_OUT/HEAD";
