#!/usr/bin/env bash

if [ -z "$KLAB_OUT" ]; then
  echo "KLAB_OUT not set, defaulting to ./out/"
  KLAB_OUT=out
fi

if [ -f "$KLAB_OUT/meta/data/$1" ] ; then
    spec_name=$(jq -r '.name' < "$KLAB_OUT/meta/data/$1")
else
    spec_name="$1";
fi

if [ ! -d "$KLAB_OUT/log" ]; then
    mkdir -p "$KLAB_OUT/log"
fi

find "$KLAB_OUT" \
     \( -wholename "*$1*" -or -wholename "*$spec_name*" \) \
     -and ! -wholename "$KLAB_OUT/log/*" \
     -exec zip "$KLAB_OUT/log/$1.zip" {} +

zip -r "$KLAB_OUT/log/$1.zip" \
    "$KLAB_OUT/prelude.smt2" \
    "$KLAB_OUT/rules.k" \
    config.json
