#!/usr/bin/env bash

if [[ $1 == --all ]]; then
  rm -fdR "$KLAB_OUT"/data
else
  comm -2 -3 <(ls "$KLAB_OUT"/data|sed 's/\(\.log\|\_blobs\)//'|uniq) <(awk 1 "$KLAB_OUT"/meta/name/*|sort)|xargs -I {} rm -fdR "$KLAB_OUT"/data/{}
  comm -2 -3 <(ls "$KLAB_OUT"/meta/data) <(awk 1 "$KLAB_OUT"/meta/name/*|sort)|xargs -I {} rm -fdR "$KLAB_OUT"/meta/data/{}
fi



