#!/usr/bin/env bash

if [ -z "$KLAB_OUT" ]; then
  KLAB_OUT=out
fi

url=$1

mkdir -p "$KLAB_OUT"/log
wget -q "$url" -P "$KLAB_OUT"/log/
unzip -qu "$KLAB_OUT/log/${url##*/}" -d "$KLAB_OUT"
# log the proof hash
basename "$url" '.zip'
