#!/usr/bin/env node
// TODO - compile needs to carry on the act
const path          = require("path");
const {docopt}      = require("docopt");

const {
  testPath,
  read
} = require("../lib/util.js");
const {
  buildDisplayInfo
}     = require('../lib/clean-evm-node.js');

const KLAB_WD_PATH = path.join(process.env.TMPDIR, "klab");

const usage = `
Usage:
  klab clean-evm-node <proofid> <blobid>
`
const cmd = docopt(usage, {
  argv: ["clean-evm-node"].concat(process.argv.slice(2))
});
const blobids = cmd['<blobid>'].split(',');
const proofid = cmd['<proofid>']
console.log(proofid);

const node = JSON.parse(read(path.join(KLAB_WD_PATH, proofid + '_blobs', blobid + '.json')));


// console.log(node);
console.log(JSON.stringify(buildDisplayInfo(node.term), false, 2));

