#!/usr/bin/env bash

set -e

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
bold=$(tput bold)
reset=$(tput sgr0)

if [ -z "$KLAB_OUT" ]; then
    echo "KLAB_OUT not set, defaulting to ./out/"
    export KLAB_OUT=out
fi

if [ -z "$KLAB_EVMS_PATH" ]; then
    echo "KLAB_EVMS_PATH must be set and point to evm-semantics!"
    exit 1
fi

echo $KLAB_EVMS_PATH

if [ -z "$TMPDIR" ]; then
    echo "TMPDIR must be set!"
    exit 1
fi

if [[ $1 == --dump ]]; then
    dump=true
    target_spec=$2
else
    dump=false
    target_spec=$1
fi

spec_hash=$("${0%/*/*}/bin/klab" hash $target_spec)

if $dump; then
    dump_flags="--state-log --state-log-path $TMPDIR/klab --state-log-id $spec_hash --state-log-events OPEN,REACHINIT,REACHTARGET,REACHPROVED,RULE,SRULE,NODE,RULEATTEMPT,IMPLICATION,Z3QUERY,Z3RESULT,CLOSE"
    dump_notice="(with ${yellow}state logging${reset})"
fi

echo "Proof ${bold}STARTING${reset}:" "$(basename $target_spec)" $dump_notice

K_OPTS=-Xmx10G \
      $KLAB_EVMS_PATH/.build/k/k-distribution/target/release/k/bin/kprove \
      $dump_flags \
      --directory $KLAB_EVMS_PATH/.build/java/ \
      --def-module RULES \
      --output-omit "<programBytes> <program> <code> <previousGas> <touchedAccounts> <interimStates> <callStack> <callData>" \
      --output-flatten "_Map_ #And" \
      --no-alpha-renaming \
      --no-sort-collections \
      --output json \
      --smt_prelude $KLAB_OUT/prelude.smt2 \
      --z3-tactic "(or-else (using-params smt :random-seed 3 :timeout 1000) (using-params smt :random-seed 2 :timeout 2000) (using-params smt :random-seed 1))" \
      $target_spec
result=$?

if [[ $result -ne 0 ]]; then
    echo "${red}Proof ${bold}REJECT${reset}:" $(basename $target_spec) $dump_notice
else
    echo "${green}Proof ${bold}ACCEPT${reset}:" $(basename $target_spec) $dump_notice
    mkdir -p $KLAB_OUT/pass && touch $KLAB_OUT/pass/$spec_hash
fi
