#!/usr/bin/env node
const xs = require("xstream").default;
const {run} = require("@cycle/run");
const {docopt} = require("docopt");
const fs = require("fs");

const cliDriver = require("../lib/cliDriver.js")
const remoteDriver = require("../lib/remoteDriver.js")
const localDriver  = require("../lib/localDriver.js");
const main = require("../lib/main.js");

const usage = `
Usage:
  klab run [options]

Options:
  --no-replay               No replay
  --remote
`

const cmd = docopt(usage, {
  argv: ["run"].concat(process.argv.slice(2))
});


const config = JSON.parse(fs.readFileSync("./config.json"));
if (fs.existsSync(config.source + ".json")) {
    config.solJson = JSON.parse(fs.readFileSync(config.source + ".json"));
    contract_path = "src" + config.source.replace('.','') + config.source.replace('./',':').replace('.sol','')
    contract_json = config.solJson.contracts[contract_path]
    config["bin_runtime"] = contract_json["bin-runtime"];
    config["sourcemap"] = contract_json["srcmap-runtime"];
    console.log(config["bin_runtime"])
//    console.log(JSON.parse(config.solJson.contracts).runtimepath)
//    config.bin_runtime = config.solJson.contracts.runtimepath
				     
}
else {
    throw config.source + ".json not in directory."
}

    

// read the spec files
[
  "spec",
  "lemmas",
//  "bin_runtime",
  "source",
//  "sourcemap"
].forEach(filetype => {
  let content = fs.readFileSync(config[filetype]).toString()
  config[filetype] = content;
})


const kDriver = cmd["--remote"]
  ? remoteDriver(config.host)
  : localDriver
  ;

config.replay = !cmd["--no-replay"];

const drivers = {
  CLI: cliDriver,
  K: kDriver,
  Settings: () => xs.of(config)
};

run(main, drivers)
