#!/usr/bin/env node
const xs = require("xstream").default;
const {run} = require("@cycle/run");
const serverDriver = require("../lib/Driver/serverDriver.js");
const localDriver  = require("../lib/Driver/localDriver.js");
const onionify = require('cycle-onionify').default;

const main = ({onion, Server, K}) => {

  const initialReducer$ = xs.of(() => ({
    peer2proof: {},
    proof2peer: {}
  }))

  return {
    Server: K,
    K: Server,
    onion: xs.merge(initialReducer$)
  };
}

const drivers = {
  Server: serverDriver(),
  K: localDriver
};

const wrappedMain = onionify(main);

run(wrappedMain, drivers)
